### ISSUE TITLE
Version 2.0.0 doesn't work

### ISSUE THREAD

**Issue by shadowhand** [RikudouSage/DynamoDbCachePsr6#14]
I can't figure out why, but upgrading to version 2.0.0 causes all calls to error with:

```
Code:    ResourceNotFoundException
Message: Cannot do operations on a non-existent table
```

Nothing about my configuration has changed, other than switching:

```diff
- use Aws\DynamoDb\DynamoDbClient;
+ use AsyncAws\DynamoDb\DynamoDbClient;
```

**Comment by shadowhand** [comment]
Yes, and yes. As I said, the only change was switching versions and replacing the client.

**Comment by RikudouSage** [comment]
Well, AWS is a little magic when it comes to guessing your configuration, it's possible the official SDK got the region from somewhere else.

Can you send a snippet of how you construct the object?

**Comment by shadowhand** [comment]
```php
final class DynamoDbCacheFactory
{
    public function __invoke(ContainerInterface $container): DynamoDbCache
    {
        return new DynamoDbCache(
            tableName: $container->get('aws.dynamodb.tables.cache'),
            client: $container->get(DynamoDbClient::class),
            prefix: $container->get('app.version'),
        );
    }
}
```

**Comment by RikudouSage** [comment]
And the `DynamoDbClient`?
